// let ayaInput = prompt("wesh");

// if(ayaInput== "hey"){
//     alert("sa marche");
// }else if(ayaInput== "levi"){
//     alert("Kennyyyyy!!!!!");
// }else if(ayaInput== "salam aleykom"){
//     alert("wa aleykom a salam");
// }else if(ayaInput=="sawarasenai"){
//     alert("kimi wa shojo nano");
// }else if(ayaInput=="shinzo wo"){
//     alert("SASAGEYOOOOOO!!!!");
// }else{
//     alert("wsh c pas dans le programme va te faire biiiip");
// }

